# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "calculator-app", "/home/vagrant/calculator-app"
  config.vm.provision :shell, path: "install-ansible.sh"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end
  config.vm.network "forwarded_port", guest: 8080, host: 8080

end